import type { Config } from "tailwindcss";
import animatePlugin from "tailwindcss-animate";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      transitionProperty: {
        width: "width",
      },
      fontFamily: {
        sans: ["var(--font-roboto)"],
      },
      screens: {
        "2sm": "481px",
        "max-2sm": { raw: "(max-width: 480px)" },
        "2smh": { raw: "(max-height: 600px)" },
        smh: { raw: "(max-height: 680px)" },
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
        "max-sm": { raw: "(max-width: 640px)" },
        "max-md": { raw: "(max-width: 768px)" },
        "max-lg": { raw: "(max-width: 1024px)" },
        "max-xl": { raw: "(max-width: 1280px)" },
        "max-2xl": { raw: "(max-width: 1536px)" },
      },
      colors: {
        // KGB Brand Colors (usando CSS variables)
        kgb: {
          red: "hsl(var(--kgb-red))",
          "red-dark": "hsl(var(--kgb-red-dark))",
          gold: "hsl(var(--kgb-gold))",
          "gold-dark": "hsl(var(--kgb-gold-dark))",
          black: "hsl(var(--kgb-black))",
        },
        // Glass Morphism
        glass: {
          "bg-from": "hsl(var(--glass-bg-from))",
          "bg-via": "hsl(var(--glass-bg-via))",
          "bg-to": "hsl(var(--glass-bg-to))",
          blur: "hsl(var(--glass-blur))",
          border: "hsl(var(--glass-border))",
        },
        // Quota Status Colors
        quota: {
          "livre-bg": "hsl(var(--quota-livre-bg))",
          "livre-border": "hsl(var(--quota-livre-border))",
          "livre-text": "hsl(var(--quota-livre-text))",
          "livre-hover": "hsl(var(--quota-livre-hover))",
          "reservado-bg": "hsl(var(--quota-reservado-bg))",
          "reservado-border": "hsl(var(--quota-reservado-border))",
          "reservado-text": "hsl(var(--quota-reservado-text))",
          "pago-bg": "hsl(var(--quota-pago-bg))",
          "pago-border": "hsl(var(--quota-pago-border))",
          "pago-text": "hsl(var(--quota-pago-text))",
          "selected-bg": "hsl(var(--quota-selected-bg))",
          "selected-border": "hsl(var(--quota-selected-border))",
          "selected-text": "hsl(var(--quota-selected-text))",
        },
        // Text Variants
        text: {
          muted: "hsl(var(--text-muted))",
          subtle: "hsl(var(--text-subtle))",
          secondary: "hsl(var(--text-secondary))",
        },
        border: {
          DEFAULT: "hsl(var(--border))",
        },
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: {
          DEFAULT: "hsl(var(--background))",
        },
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          5: "hsla(var(--primary-5))",
          10: "hsla(var(--primary-10))",
          20: "hsla(var(--primary-20))",
          30: "hsla(var(--primary-30))",
          40: "hsla(var(--primary-40))",
          50: "hsla(var(--primary-50))",
          60: "hsla(var(--primary-60))",
          70: "hsla(var(--primary-70))",
          80: "hsla(var(--primary-80))",
          90: "hsla(var(--primary-90))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          5: "hsla(var(--secondary-5))",
          10: "hsla(var(--secondary-10))",
          20: "hsla(var(--secondary-20))",
          30: "hsla(var(--secondary-30))",
          40: "hsla(var(--secondary-40))",
          50: "hsla(var(--secondary-50))",
          60: "hsla(var(--secondary-60))",
          70: "hsla(var(--secondary-70))",
          80: "hsla(var(--secondary-80))",
          90: "hsla(var(--secondary-90))",
        },
        tertiary: {
          DEFAULT: "hsl(var(--tertiary))",
          foreground: "hsl(var(--tertiary-foreground))",
          hover: "hsl(var(--tertiary-hover))",
          5: "hsla(var(--tertiary-5))",
          10: "hsla(var(--tertiary-10))",
          20: "hsla(var(--tertiary-20))",
          30: "hsla(var(--tertiary-30))",
          40: "hsla(var(--tertiary-40))",
          50: "hsla(var(--tertiary-50))",
          60: "hsla(var(--tertiary-60))",
          70: "hsla(var(--tertiary-70))",
          80: "hsla(var(--tertiary-80))",
          90: "hsla(var(--tertiary-90))",
        },
        quaternary: {
          DEFAULT: "hsl(var(--quaternary))",
          foreground: "hsl(var(--quaternary-foreground))",
          hover: "hsl(var(--quaternary-hover))",
          5: "hsla(var(--quaternary-5))",
          10: "hsla(var(--quaternary-10))",
          20: "hsla(var(--quaternary-20))",
          30: "hsla(var(--quaternary-30))",
          40: "hsla(var(--quaternary-40))",
          50: "hsla(var(--quaternary-50))",
          60: "hsla(var(--quaternary-60))",
          70: "hsla(var(--quaternary-70))",
          80: "hsla(var(--quaternary-80))",
          90: "hsla(var(--quaternary-90))",
        },
        quinary: {
          DEFAULT: "hsl(var(--quinary))",
          foreground: "hsl(var(--quinary-foreground))",
          hover: "hsl(var(--quinary-hover))",
          5: "hsla(var(--quinary-5))",
          10: "hsla(var(--quinary-10))",
          20: "hsla(var(--quinary-20))",
          30: "hsla(var(--quinary-30))",
          40: "hsla(var(--quinary-40))",
          50: "hsla(var(--quinary-50))",
          60: "hsla(var(--quinary-60))",
          70: "hsla(var(--quinary-70))",
          80: "hsla(var(--quinary-80))",
          90: "hsla(var(--quinary-90))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          hover: "hsl(var(--destructive-hover))",
          5: "hsla(var(--destructive-5))",
          10: "hsla(var(--destructive-10))",
          20: "hsla(var(--destructive-20))",
          30: "hsla(var(--destructive-30))",
          40: "hsla(var(--destructive-40))",
          50: "hsla(var(--destructive-50))",
          60: "hsla(var(--destructive-60))",
          70: "hsla(var(--destructive-70))",
          80: "hsla(var(--destructive-80))",
          90: "hsla(var(--destructive-90))",
        },

        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          hover: "hsl(var(--warning-hover))",
          5: "hsla(var(--warning-5))",
          10: "hsla(var(--warning-10))",
          20: "hsla(var(--warning-20))",
          30: "hsla(var(--warning-30))",
          40: "hsla(var(--warning-40))",
          50: "hsla(var(--warning-50))",
          60: "hsla(var(--warning-60))",
          70: "hsla(var(--warning-70))",
          80: "hsla(var(--warning-80))",
          90: "hsla(var(--warning-90))",
        },

        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
          hover: "hsl(var(--info-hover))",
          5: "hsla(var(--info-5))",
          10: "hsla(var(--info-10))",
          20: "hsla(var(--info-20))",
          30: "hsla(var(--info-30))",
          40: "hsla(var(--info-40))",
          50: "hsla(var(--info-50))",
          60: "hsla(var(--info-60))",
          70: "hsla(var(--info-70))",
          80: "hsla(var(--info-80))",
          90: "hsla(var(--info-90))",
        },

        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          hover: "hsl(var(--success-hover))",
          5: "hsla(var(--success-5))",
          10: "hsla(var(--success-10))",
          20: "hsla(var(--success-20))",
          30: "hsla(var(--success-30))",
          40: "hsla(var(--success-40))",
          50: "hsla(var(--success-50))",
          60: "hsla(var(--success-60))",
          70: "hsla(var(--success-70))",
          80: "hsla(var(--success-80))",
          90: "hsla(var(--success-90))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
          gradient: "hsl(var(--card-gradient))",
        },
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic": "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      animation: {
        scroll: "scroll 40s linear infinite",
        scroll2: "scroll var(--animation-duration, 40s) var(--animation-direction, forwards) linear infinite",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        aurora: "aurora 60s linear infinite",
        "gradient-x": "gradient-x 3s ease infinite",
      },
      backgroundSize: {
        "size-200": "200% 200%",
      },
      // Adiciona componentes reutilizáveis
      components: {
        "glass-card": "relative overflow-hidden rounded-2xl",
      },
      keyframes: {
        scroll: {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(calc(-250px * 14))" },
        },
        scroll2: {
          to: {
            transform: "translate(calc(-50% - 0.5rem))",
          },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "gradient-x": {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        aurora: {
          "0%": { backgroundPosition: "50% 50%, 50% 50%" },
          "100%": { backgroundPosition: "350% 50%, 350% 50%" },
        },
      },
      // Tipografia customizada como utilitários Tailwind
      fontSize: {
        "display-01": "4.5rem",
        "display-02": "4rem",
        "heading-01": "3.5rem",
        "heading-02": "3rem",
        "heading-03": "2rem",
        "heading-04": "1.75rem",
        "heading-05": "1.5rem",
        "body-title": "1.25rem",
        "body-paragraph": "1rem",
        "body-callout": "0.875rem",
        "body-caption": "0.75rem",
      },
      fontWeight: {
        light: "300",
        medium: "500",
        bold: "700",
      },
    },
  },
  plugins: [
    animatePlugin,
    function ({ addUtilities }: any) {
      const newUtilities = {
        ".scrollbar-thin": {
          scrollbarWidth: "thin",
          scrollbarColor: "rgb(var(--rev-azul-principal))",
        },
        ".scrollbar-webkit": {
          "&::-webkit-scrollbar": {
            width: "8px",
          },
          "&::-webkit-scrollbar-thumb": {
            backgroundColor: "rgb(var(--rev-azul-principal))",
            borderRadius: "20px",
            border: "1px solid white",
          },
        },
        // Utilitários de tipografia customizados
        ".display-01": { fontWeight: "700", fontSize: "4.5rem", lineHeight: "1.2" },
        ".display-02": { fontWeight: "700", fontSize: "4rem", lineHeight: "1.2" },
        ".heading-01": { fontWeight: "700", fontSize: "3.5rem", lineHeight: "1.2" },
        ".heading-02-bold": { fontWeight: "700", fontSize: "3rem", lineHeight: "1.2" },
        ".heading-02-medium": { fontWeight: "500", fontSize: "3rem", lineHeight: "1.2" },
        ".heading-02": { fontWeight: "400", fontSize: "3rem" },
        ".heading-02-light": { fontWeight: "300", fontSize: "3rem" },
        ".heading-03-bold": { fontWeight: "700", fontSize: "2rem" },
        ".heading-03-medium": { fontWeight: "500", fontSize: "2rem" },
        ".heading-03": { fontWeight: "400", fontSize: "2rem" },
        ".heading-04-bold": { fontWeight: "700", fontSize: "1.75rem" },
        ".heading-04-medium": { fontWeight: "500", fontSize: "1.75rem" },
        ".heading-04": { fontWeight: "400", fontSize: "1.75rem" },
        ".heading-04-light": { fontWeight: "300", fontSize: "1.75rem" },
        ".heading-05-bold": { fontWeight: "700", fontSize: "1.5rem" },
        ".heading-05-medium": { fontWeight: "500", fontSize: "1.5rem" },
        ".heading-05": { fontWeight: "400", fontSize: "1.5rem" },
        ".heading-05-light": { fontWeight: "300", fontSize: "1.5rem" },
        ".body-title-bold": { fontWeight: "700", fontSize: "1.25rem" },
        ".body-title-medium": { fontWeight: "500", fontSize: "1.25rem" },
        ".body-title": { fontSize: "1.25rem" },
        ".body-title-light": { fontWeight: "300", fontSize: "1.25rem" },
        ".body-paragraph-bold": { fontWeight: "700", fontSize: "1rem" },
        ".body-paragraph-medium": { fontWeight: "500", fontSize: "1rem" },
        ".body-paragraph": { fontWeight: "400", fontSize: "1rem" },
        ".body-paragraph-light": { fontWeight: "300", fontSize: "1rem" },
        ".body-callout-bold": { fontWeight: "700", fontSize: "0.875rem" },
        ".body-callout-medium": { fontWeight: "500", fontSize: "0.875rem" },
        ".body-callout": { fontWeight: "400", fontSize: "0.875rem" },
        ".body-callout-light": { fontWeight: "300", fontSize: "0.875rem" },
        ".body-caption-bold": { fontWeight: "700", fontSize: "0.75rem" },
        ".body-caption-medium": { fontWeight: "500", fontSize: "0.75rem" },
        ".body-caption": { fontWeight: "400", fontSize: "0.75rem" },
        ".body-caption-light": { fontWeight: "300", fontSize: "0.75rem" },
        // Glass card utilities (usando CSS variables)
        ".glass-card": {
          position: "relative",
          overflow: "hidden",
          borderRadius: "1rem",
        },
        ".glass-bg": {
          position: "absolute",
          overflow: "hidden",
          borderRadius: "1rem",
          inset: "0",
          background:
            "linear-gradient(to bottom right, hsl(var(--glass-bg-from)), hsl(var(--glass-bg-via)), hsl(var(--glass-bg-to)))",
        },
        ".glass-blur": {
          position: "absolute",
          overflow: "hidden",
          borderRadius: "1rem",
          inset: "0",
          backdropFilter: "blur(24px)",
          backgroundColor: "hsl(var(--glass-blur))",
        },
        ".glass-border": {
          position: "absolute",
          overflow: "hidden",
          inset: "0",
          border: "1px solid hsl(var(--glass-border))",
          borderRadius: "1rem",
        },
        ".glass-hover": {
          position: "absolute",
          inset: "0",
          opacity: "0",
          transition: "opacity 700ms",
          "&:hover": {
            opacity: "0.3",
          },
        },
        ".glass-hover-gradient": {
          position: "absolute",
          inset: "0",
          background: "linear-gradient(to right, #E60000, #FFD700, #E60000)",
          backgroundSize: "200% 200%",
          animation: "gradient-x 3s ease infinite",
          filter: "blur(24px)",
        },
      };
      addUtilities(newUtilities, ["responsive", "hover"]);
    },
    require("tailwind-scrollbar-hide"),
  ],
  safelist: [
    "*:data-[slot=card]:bg-red",
    "*:data-[slot=card]:bg-gradient-to-t",
    "*:data-[slot=card]:shadow-xs",
    // adicione outras que quiser usar
  ],
};

export default config;
